// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACwwUZJul-ZVr-HhgJ3GE3LgZRRnCraSY',
    appId: '1:386011707942:web:564bf99897fed906ad44e7',
    messagingSenderId: '386011707942',
    projectId: 'hydra-8008b',
    authDomain: 'hydra-8008b.firebaseapp.com',
    storageBucket: 'hydra-8008b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2VLEyyTcQxzmUm7BZEHxPgHnhQDaT0ow',
    appId: '1:386011707942:android:47a5cb5c9c83e824ad44e7',
    messagingSenderId: '386011707942',
    projectId: 'hydra-8008b',
    storageBucket: 'hydra-8008b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCEEXNyiKIUgyCV59pZsQrC-e3nNW95yc',
    appId: '1:386011707942:ios:1a3a255c3eb94869ad44e7',
    messagingSenderId: '386011707942',
    projectId: 'hydra-8008b',
    storageBucket: 'hydra-8008b.appspot.com',
    iosBundleId: 'com.example.translatorApp',
  );
}
